### ISSUE TITLE
Set State messes up alarm panel attributes

### ISSUE THREAD

**Issue by DNKROZ** [segalion/securitasdirect#5]
Hello.

First, thank you for providing an interface with the spanish Securitas Direct user area and the integration with HA, this has brought some usability improvements to my alarm system and avoid me from scrapping it completely due to the lack of integrations available.

I'm currently using it with node-red instead HA automations, had to tweak some bits to make it work, but it finally works ok, and even reports the arming, disarming, armed statuses, sometimes the actions to the web site (via the script) fail, but since there is a sensor status update it doesn't matter (unless you want a real-time status update and it's not possible, the Securitas Web is very "flawed" (to say the least).

The problem is with the Alarm panel integration with HA, I know your example doesn't include a "code" section, but when I try to configure this alarm panel with that option, the update from the script to this component seems to delete all attributes, taking the code with it and thus, making the panel unusable for future actions.

Most probably you are aware of this issue (since the example avoid setting a code) but I wanted to point this out since it should be a great improvement to be able to use this with an access code.

Best regards.

**Comment by segalion** [comment]
Sorry about so low response level here.
I have this project a little abandonend. Could be great to create a python custom-component around securitas-direct web, like actual verisure platform. The problem here is the basis where construct something that has some guarantee of durability over time, because actual securitas direct web is "archaic". A web server of the last century: no rest-api with websockets to avoid polling, with a certain security modernity, for example, it is necessary to download more than 500Kb for each poll, etc.

However, it is likely that when I have some more time I will review the entire project to create an alarm component that has a keyboard option, to be able to remove my current security keypad (what a shit !!!) for a cheap tablet on the wall with HA, which in addition to replacing the keyboard allows me to do many more things

Thanks.

**Comment by DNKROZ** [comment]
Hello, thanks for the response and glad for the news about it... I didn't have any hopes for the Securitas alarm to be integrated with Home Assistant so any news is good news, if you can manage the time to write a custom component it'll be greatly appreciated, in the meanwhile in its current state is "usable" :)

Best regards.

**Comment by segalion** [comment]
A Home Assistant custom component has been created, based on mobile API that works mutch better than web scraping.
So I am going to close this.

Thanks
